### PR TITLE
doc_extract: output json instead of python dict to stdout.

### LINKED ISSUE #4: `doc_extract` outputs a Python dict, not JSON to stdout
If you run
```bash
doc_extract -s repos.txt -o docstrings.json
```
`docstrings.json` will contain the extracted docstrings in JSON format.

But if you run
```bash
doc_extract -s repos.txt >docstrings.json
```
the contents will be a Python dictionary representation instead of JSON.

### PR DESCRIPTION
**Pull request by real-yfprojects**
Fixes #4. Most of the time python dicts look like json but not always.

* bin/doc_extract/doc_extract/driver.py (Driver.run)

### CODE REVIEW

**Comment by real-yfprojects** [comment]
I noticed that the output of `doc_extract` changes in order. Should we fix that?

**Comment by akaihola** [comment]
> I noticed that the output of `doc_extract` changes in order. Should we fix that?

I remember noticing the same, and this might have been one of the things I asked Terrence about – although I can't find any trace of it now. Probably order doesn't matter.

**Comment by real-yfprojects** [comment]
> remember noticing the same, and this might have been one of the things I asked Terrence about

Do you mean this question about `bnf_to_cnf`? https://github.com/akaihola/darglint2/pull/1#discussion_r1096996459

**Comment by real-yfprojects** [comment]
> Could you include an example in a comment here?

Running

```bash
echo https://github.com/borgbase/vorta > repos.txt
doc_extract -s repos.txt -o docstrings1.json
doc_extract -s repos.txt -o docstrings2.json
npx prettier --write docstrings*.json
diff docstrings1.json docstrings2.json
```

```diff
2655,2656c2655,2656
<         "filename": "/tmp/tmpm6u0_arq/src/vorta/views/partials/treemodel.py",
<         "docstring": "Return a string representation of a path.",
---
>         "filename": "/tmp/tmpmwe7wdml/src/vorta/views/partials/treemodel.py",
>         "docstring": "Get p2 relative to p1.",
2668,2669c2668,2669
<         "filename": "/tmp/tmpm6u0_arq/src/vorta/views/partials/treemodel.py",
<         "docstring": "Get p2 relative to p1.",
---
>         "filename": "/tmp/tmpmwe7wdml/src/vorta/views/partials/treemodel.py",
>         "docstring": "Return a string representation of a path.",

```

**Comment by akaihola** [comment]
> Do you mean this question about `bnf_to_cnf`? [#1 (comment)](https://github.com/akaihola/darglint2/pull/1#discussion_r1096996459)

Yes, that's the one I had in mind. But it seemed to be about a different kind of change in ordering.

Could it be that the order of `doc_extract` output depends on the Python version being used?

Is the order significant when the JSON file is used? If not, would it make sense to sort the output to make tests stable?

**Comment by real-yfprojects** [comment]
> Could it be that the order of `doc_extract` output depends on the Python version being used?

No, I used the same version, see steps to reproduce above.

> Is the order significant when the JSON file is used? If not, would it make sense to sort the output to make tests stable?

It is not significant. However file diffs will show changes although nothing changed.

**Review by akaihola — APPROVED** [review]

**Pull request merged**
