### PR TITLE
Setup .editorconfig and pre-commit. Format/fix codebase. Fix bug noticed by flake8.

### PR DESCRIPTION
**Pull request by real-yfprojects**
This autoformats the codebase. I suggest fast forward merging.
Fixes loading log_level from config file. Flake8 noticed that the `log_level` loaded from the file wasn't used. So I passed it on to `Configuration`.

Didn't test anything yet.

### CODE REVIEW

**Comment by real-yfprojects** [comment]
I ran all the tests including integration tests with tox. This seems to work.

**Comment by akaihola** [comment]
Thanks for the contribution! I still prefer to do the 1.8.2 release with as few changes as possible, and start improving in 1.8.3. Hence milestone 1.8.3.

**Comment by akaihola** [comment]
1.8.2 has now been released. `main` now includes a GitHub Workflow which runs the test suite using Tox on Python versions 3.6–3.9. If you rebase on `main`, you'll get the tests runs here, too. And dropping Python 3.6 from the workflow is probably most logically done in #15 after rebasing that one as well.

>I suggest fast forward merging.

Just for this pull request, or as a convention for the repository in general?

**Comment by real-yfprojects** [comment]
> Just for this pull request

For this one. A merge will not run the autoformatting on the merged changes not included in this branch. The same goes for a rebase through the ui. `.git-blame-ignore-revs` works with fixed commit hashes that's why squashing (and simply rebasing) doesn't work.

**Comment by akaihola** [comment]
>fast forward merging.

[Looks like GitHub does not support this](https://stackoverflow.com/a/65314973/15770), so I guess I need to `git merge --ff-only` and push instead.

**Comment by real-yfprojects** [comment]
Yes, that's how I often do it.

**Comment by real-yfprojects** [comment]
I ran into a not so small problem. I configured darglint2 so we can use it for qa in this repository. However the tests load their config from the configuration file too and fail since they rely on the default configuration. IMO tests should run in a stable, strictly defined environment. The config should also be dynamically editable to test different configurations. According to source comments this is currently not possible. So this could be added as a task to a future milestone. For now I implemented a fixture that overrides the config with its default values.

**Review by akaihola — APPROVED** [review]

**Comment by akaihola** [comment]
I rebased, updated `.git-blame-ignore-revs` and fast-forward merged to `master`.

**Pull request closed without merging**
